# this boolean is set by the bed set and bed clear automations
# in the event the sensor breaks this can be set manually
input_boolean:
  in_bed:
    name: Bed Occupancy
    initial: off
    icon: mdi:hotel

# sensor for the mass published by the device
sensor:
  - platform: mqtt
    state_topic: "/home/bedroom/bed/load"
    name: Bed Mass
    unit_of_measurement: "kg"

# zeros out the current reading
script:
  zero_bed:
    alias: Tare Bed
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "/home/bedroom/bed/tare"
          payload: '0'

automation:
  # sets the in_bed boolean over a certain mass
  - alias: bed set
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_mass
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_mass
          above: '50'
        - condition: state
          entity_id: device_tracker.alex
          state: 'HOME'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.in_bed

  # clears the in_bed boolean under a certain mass
  - alias: bed clear
    hide_entity: True
    trigger:
      platform: state
      entity_id: sensor.bed_mass
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bed_mass
          below: '20'
        - condition: state
          entity_id: device_tracker.alex
          state: 'HOME'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.in_bed

  # tasks to perform when in bed
  - alias: Bed Occupied Tasks
    trigger:
      platform: state
      entity_id: input_boolean.in_bed
      to: 'on'
    condition:
      condition: time
      after: '20:00:00'
      before: '04:00:00'
    action:
      - service: light.turn_off
        entity_id: group.bedroom_lights
        data:
          transition: 10
      - service: switch.turn_off
        entity_id: switch.heater